apiVersion: v1
kind: Service
metadata:
  name: web-auth-svc
  namespace: default
  labels:
    app: web-auth
spec:
  type: ClusterIP
  selector:
    app: web-auth
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80