# Headless Service with selector
kind: Service
apiVersion: v1
metadata:
  name: pod-test-svc-01
  namespace: default
  labels:
    app: pod-test
spec:
  selector:
    app: pod-test
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
---
# Headless Service without selector
kind: Service
apiVersion: v1
metadata:
  name: pod-test-svc-02
  namespace: default
  labels:
    app: pod-test
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node