# In order this example to work in the cluster should be running the vault-agent-injector.
# Also a vault server should be available somewhere where vault-agent-injector will retrieve secrets from
# More Info:
# https://learn.hashicorp.com/tutorials/vault/agent-kubernetes
# https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-injector-test
  namespace: devops
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'dev-dsproject-devops'
        vault.hashicorp.com/agent-inject-secret-config: 'dev/secret/devops/dummy'
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "dev/secret/devops/dummy" -}}
            export dummy_secret="{{ .Data.dummy_secret }}"
          {{- end }}
    spec:
      containers:
        - name: test
          image: busybox:latest
          args:
            ['sh', '-c', 'source /vault/secrets/config && printenv | sort && sleep 3600']
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 300m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 20Mi