apiVersion: v1
kind: Pod
metadata:
  name: redispod
spec:
  containers:
  - image: redis
    name: redisdb
    volumeMounts:
    - name: redis-data
      mountPath: /data
    ports:
    - containerPort: 6379
      protocol: TCP
    resources:
      limits:
        cpu: "200m"
        memory: "100Mi"
      requests:
        cpu: "20m"
        memory: "20Mi"
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: redisdb-pvc