apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - image: busybox:1.28
    name: busybox
    command:
      - /bin/sh
      - -c
    args:
      - sleep 3600
    volumeMounts:
    - name: data
      mountPath: /data
    resources:
      limits:
        cpu: "200m"
        memory: "100Mi"
      requests:
        cpu: "20m"
        memory: "20Mi"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-hostpath