apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  restartPolicy: Always
  containers:
  - image: busybox:1.28.4
    name: busybox
    command:
      - sleep
      - "3600"
    resources:
      limits:
        cpu: "200m"
        memory: "100Mi"
      requests:
        cpu: "20m"
        memory: "20Mi"
    volumeMounts:
    - name: log
      mountPath: /log
      readOnly: true
  volumes:
  - name: log
    hostPath:
      path: /var/log/