apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  restartPolicy: Always
  serviceAccount: aws-cli
  containers:
  - image: amazon/aws-cli:latest
    name: aws-cli
    command:
      - sleep
      - "3600"
    resources:
      limits:
        cpu: "200m"
        memory: "100Mi"
      requests:
        cpu: "20m"
        memory: "20Mi"