apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - image: linuxacademycontent/kubeserve
    name: kubeserve
    livenessProbe:
      httpGet:
        path: /
        port: 80
    resources:
      requests:
        cpu: 300m
        memory: 10Mi
      limits:
        cpu: 800m
        memory: 20Mi